use bevy::prelude::*;

pub const CAMERA_FOLLOW_SPEED: f32 = 10.;
pub const CAMERA_ZOOM_AMOUNT: f32 = 5.;
pub const DEFAULT_CAMERA_ZOOM: f32 = 1.;
const CAMERA_ZOOM_OFFSET: f32 = 0.4;
pub const CAMERA_ZOOM_IN_LIMIT: f32 = DEFAULT_CAMERA_ZOOM - CAMERA_ZOOM_OFFSET;
pub const CAMERA_ZOOM_OUT_LIMIT: f32 = DEFAULT_CAMERA_ZOOM + CAMERA_ZOOM_OFFSET;